config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: "pages#home"
  get "projects", to: "pages#projects"
  get "contact", to: "pages#contact"
  get "resume", to: "pages#resume"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
    @contact
  end

  def resume
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.with(user: @user).welcome_email.deliver_now

        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
        p 'yes'
      else

        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        p 'no'
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :login)

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stan's Portfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('programming.png') %>
  </head>
</head>
<body>
  <%# render 'pages/header' %>
  <%= yield %>
</body>
</html>

app/views/pages/_cta_card.html.erb
<div class="cta-box">
  <div class="d-flex">
    <div class="row">
      <div class="col-md-4">
        <div class="d-flex align-items-end justify-content-end">
          <%= image_tag 'https://avatars.githubusercontent.com/u/67323109?v=4', alt: "text", class: "profile-pic" %>
        </div>
      </div>
      <div class="col-md-8">
        <div class="cta-title d-flex align-items-center justify-content-center mt-2">
          <h1>Hello! I'm a <span class="red-text">{</span>full-stack<span class="red-text">}</span> developer...</h1>
        </div>
      </div>
    </div>
  </div>
  <p class="cta-text mt-3">
    Hi, I'm Stan! I make web apps with Ruby, Python, JavaScript, CSS,
    and HTML. My solid foundation in Ruby on Rails lets me create seamless,
    user-friendly web applications from front to back. My goal is to build
    responsive and interactive solutions that meet clients' needs and exceed
    their expectations.
  </p>
  <div class="mt-4 d-flex gap-3">
    <%#= link_to 'resume 🚀', resume_path, class: "res-button"  %>
    <%#= link_to 'contact ☎️', contact_path, class: "res-button"  %>
  </div>
</div>

app/views/pages/_header.html.erb
<header>
  <div class="d-flex align-items-center">
    <div class="logo me-3">
      <%= image_tag 'https://avatars.githubusercontent.com/u/133672174?v=4', alt: "text"%>
    </div>
    <div class="nav">
      <ul class="d-flex">
        <li class="me-3"><a href="#">Content</a></li>
        <li class="me-3"><a href="#">Projects</a></li>
        <li><a href="#">Resume</a></li>
      </ul>
    </div>
  </div>
</header>

app/views/pages/_project_card.html.erb
<% rails_icon = 'https://pbs.twimg.com/profile_images/691206086955790336/CDMbA57p_400x400.png' %>
<% ruby_icon = 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ruby_logo.svg/2048px-Ruby_logo.svg.png' %>
<% js_icon = 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/800px-JavaScript-logo.png' %>
<% html_icon = 'https://cdn-icons-png.flaticon.com/512/732/732212.png' %>
<% css_icon = 'https://cdn4.iconfinder.com/data/icons/iconsimple-programming/512/css-512.png' %>
<% python_icon = 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1869px-Python-logo-notext.svg.png' %>
<% xml_icon = 'https://www.psdevwiki.com/vita/images/f/fb/Xml-logo.png' %>
<% java_icon = 'https://www.shareicon.net/data/512x512/2016/09/23/833700_windows_512x512.png' %>
<% bash_logo = 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Bash_Logo_Colored.svg/2048px-Bash_Logo_Colored.svg.png' %>
<div class="row project-card mb-5 w-80">
  <div class="col-4 p-3 d-flex align-items-center justify-content-center">
    <%= image_tag img_link, alt: "Project Image", class: "card-pic" %>
  </div>
  <div class="col-8 p-3">
    <%= link_to project_title, '#',  class: 'proj-head-text m-0 text-decoration-none context-menu' %>
    <%= link_to github_link, target: :_blank, class: 'proj-head m-0 text-decoration-none' do %>
      <%= content_tag(:i, '', class: 'fa-brands fa-github') %>
    <% end %>
    <% if !link.empty? %>
      <%= link_to link, target: :_blank, class: 'proj-head m-0 text-decoration-none' do %>
        <%= content_tag(:i, '', class: 'fa-solid fa-up-right-from-square') %>
      <% end %>
    <% end %>
    <p class="proj-p"><%= project_text %></p>
    <div class="d-flex gap-2 justify-content-end">
      <% stack_icons = { 'js' => js_icon, 'ruby' => ruby_icon, 'rails' => rails_icon, 'html' => html_icon, 'css' => css_icon, 'python' => python_icon, 'xml' => xml_icon, 'java' => java_icon, 'bash' => bash_logo } %>
      <% project_stack.each do |stack| %>
        <% if stack_icons.key?(stack.downcase) %>
          <%= image_tag stack_icons[stack.downcase], alt: "#{stack} Icon", class: "stack-pic" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!-- app/views/your_controller_name/home.html.erb -->
<div id="background"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vanta/0.5.21/vanta.globe.min.js"></script>
<script>
  VANTA.GLOBE({
    el: "#background",
    color: 0x6a4c93,
    color2: 0xff3f81,
    backgroundColor: 0x121012,
    size: 1.6,
    speed: 0.2
  });
</script>
<div class="content">
  <div class="row w-100 h-100">
    <div class="col-md-6 d-flex align-items-center justify-content-start h-100">
      <%= render 'cta_card' %>
    </div>
    <div class="col-md-6 d-flex align-items-center justify-content-center h-100">
      <!-- Add content here if needed -->
    </div>
  </div>
</div>
<div class="container d-flex flex-column align-content-center">
  <div id="projects-1" class="row gap-4 justify-content-center">
    <div class="col custom-card-width">
      <%= render partial: 'project_card', locals: { img_link: 'https://cdn-icons-png.flaticon.com/512/7011/7011353.png', project_text: 'An automation app used for creating short-form story videos for social media.', project_title: 'Shortify', github_link: 'https://github.com/dev-stan/shortify', project_stack: ['rails', 'js', 'html', 'css'], link: 'https://google.com' } %>
    </div>
    <div class="col custom-card-width">
      <%= render partial: 'project_card', locals: { img_link: 'https://cdn-icons-png.flaticon.com/512/11132/11132347.png', project_text: 'Similar to AirBnb, enables users to rent out and borrow dogs in their area.', project_title: 'DogBnB', github_link: 'https://github.com/kimtecson/share-your-dog', project_stack: ['rails', 'js', 'html', 'css'], link: 'https://bark-bnb-aed10ebed58b.herokuapp.com' } %>
    </div>
    <div class="col custom-card-width">
      <%= render partial: 'project_card', locals: { img_link: 'https://cdn-icons-png.flaticon.com/512/9732/9732800.png', project_text: 'Discord bot which makes use of multiple apis and customizes messages.', project_title: 'Utey Bot', github_link: 'https://github.com/dev-stan/Utey1.3', project_stack: ['python'], link: '' } %>
    </div>
  </div>
  <div id="projects" class="row gap-4 justify-content-center">
    <div class="col custom-card-width">
      <%= render partial: 'project_card', locals: { img_link: 'https://cdn-icons-png.flaticon.com/512/2152/2152502.png', project_text: 'Simple block chain technology application using Python.', project_title: 'Freechain', github_link: 'https://github.com/dev-stan/freechain', project_stack: ['python', 'html', 'css'], link: '' } %>
    </div>
    <div class="col custom-card-width">
      <%= render partial: 'project_card', locals: { img_link: 'https://cdn-icons-png.flaticon.com/512/6008/6008504.png', project_text: 'Bash and Python scripts to create a reverse shell using netcat.', project_title: 'Reverse Shell', github_link: 'https://github.com/kimtecson/ncat', project_stack: ['python', 'bash'], link: '' } %>
    </div>
    <div class="col custom-card-width">
      <%= render partial: 'project_card', locals: { img_link: 'https://cdn-icons-png.flaticon.com/512/462/462887.png', project_text: 'Minecraft plugin adding extra functionality for Paper Java servers.', project_title: 'Anvil', github_link: 'https://github.com/dev-stan/anvilrepair', project_stack: ['java', 'xml'], link: '' } %>
    </div>
  </div>
</div>

app/views/pages/projects.html.erb
<div id="background"></div>
<script src="https://cdn.jsdelivr.net/npm/vanta@0.5.24/dist/vanta.trunk.min.js"></script>
<script>
  VANTA.TRUNK({
    el: "#background",
    mouseControls: true,
    touchControls: true,
    gyroControls: false,
    minHeight: 200.00,
    minWidth: 200.00,
    scale: 1.00,
    scaleMobile: 1.00
  })
</script>
<div class="content">
  <div class="row w-100 h-100">
    <div class="col-6 d-flex align-items-center justify-content-start h-100">
      <div class="cta-box">
        <div class="d-flex">
          <div class="row">
            <div class="col-4">
              <div class="d-flex align-items-end justify-content-end">
                <%= image_tag 'https://avatars.githubusercontent.com/u/133672174?v=4', alt: "text", class: "profile-pic" %>
              </div>
            </div>
            <div class="col-8">
              <div class="d-flex align-items-center justify-content-center mt-2">
                <h1>Hello! I'm a <span class="red-text">{</span>full-stack<span class="red-text">}</span> developer...</h1>
              </div>
            </div>
          </div>
        </div>
        <p class="mt-3">
          Hi, I'm stan! I make web apps with Ruby, Python, JavaScript, CSS,
          and HTML. My solid foundation in Ruby on Rails lets me create seamless,
          user-friendly web applications from front to back. My goal is to build
          responsive and interactive solutions that meet clients' needs and exceed
          their expectations.
        </p>
        <div class="mt-4 d-flex gap-3">
          <%= link_to 'resume 🚀', '#', class: "res-button"  %>
          <%= link_to 'projects 🕹️', projects_path, class: "res-button"  %>
        </div>
      </div>
    </div>
    <div class="col-6 d-flex align-items-center justify-content-center h-100"></div>
  </div>
</div>

app/views/pages/resume.html.erb
<!-- app/views/your_controller_name/home.html.erb -->
<div id="background"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vanta/0.5.21/vanta.globe.min.js"></script>
<script>
  VANTA.GLOBE({
    el: "#background",
    color: 0x6a4c93,
    color2: 0xff3f81,
    backgroundColor: 0x0E0F0F,
    size: 1.6,
    speed: 0.2
  });
</script>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <div class="contact_form">
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <%= f.input :name, label: false, input_html: { class: 'input' } %>
      <%= f.input :email, label: false, input_html: { class: 'input' } %>
      <%= f.input :login, label: false, input_html: { class: 'input' } %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div id="background"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.fog.min.js"></script>
<script>
  VANTA.FOG({
    el: "#background",
    mouseControls: true,
    touchControls: true,
    gyroControls: false,
    minHeight: 200.00,
    minWidth: 200.00,
    highlightColor: 0x413744,
    midtoneColor: 0x4715b0,
    lowlightColor: 0x0,
    baseColor: 0xd0b0b,
    blurFactor: 0.90,
    speed: 1.20,
    zoom: 0.20
  })
</script>
<div class="container">
  <div class="row", style="height: 100vh">
    <div class="col-6"></div>
    <div class="col-6 d-flex align-items-center justify-content-center">
      <%= render "form", user: @user %>
    </div>
  </div>
</div>